name = "SqueakyCraft"
version = "Alpha-v0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88ee4833980a408d48eb3e81a295dcf5d4e5aae01bf87c761e93157e66172d19"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
